/// Integration tests: verify that vdbscan produces the same clustering as the
/// scikit-learn reference stored in the ground-truth PLY files generated by
/// scripts/synthetic-data.py.
///
/// Each PLY file carries a header comment of the form:
///   comment vdbscan eps=0.35 min_pts=8 n_clusters=13 n_noise=142 sizes=40,55,...
///
/// For every file in SYNTHETIC_DIR (a compile-time path baked in by CMake) the
/// test suite:
///   1. Parses eps / min_pts and re-runs vdbscan on the stored point cloud.
///   2. Checks that the number of clusters matches the reference exactly.
///   3. Checks that noise count is within ±NOISE_TOL_FRAC of the reference
///      (a small tolerance absorbs border-point ambiguity).
///   4. Checks that the sorted cluster-size multiset matches within ±SIZE_TOL
///      per cluster (same rationale).

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <catch2/catch_test_macros.hpp>

#include <vdbscan/vdbscan.hpp>

using namespace vdbscan;

namespace fs = std::filesystem;

// ─────────────────────────────────────────────────────────────────────────────
// Tolerances
// ─────────────────────────────────────────────────────────────────────────────

/// Absolute tolerance on per-cluster point count (border-point ambiguity).
static constexpr std::size_t SIZE_TOL = 5;

/// Fractional tolerance on total noise count; also lower-bounded by SIZE_TOL.
static constexpr double NOISE_TOL_FRAC = 0.05;

// ─────────────────────────────────────────────────────────────────────────────
// PLY header metadata
// ─────────────────────────────────────────────────────────────────────────────

struct PlyMeta {
    float                    eps        = 0.f;
    int                      min_pts    = 0;
    int                      n_clusters = 0;
    int                      n_noise    = 0;
    std::vector<std::size_t> sizes; // sorted ascending, one entry per cluster
};

/// Parse a key=value token stream.  The first token is "vdbscan" (no '='), so
/// it is skipped automatically.  sizes= carries a comma-separated list.
static PlyMeta parse_meta(const std::string &comment) {
    PlyMeta m;
    std::istringstream ss(comment);
    std::string tok;
    while (ss >> tok) {
        const auto eq = tok.find('=');
        if (eq == std::string::npos)
            continue;
        const std::string key = tok.substr(0, eq);
        const std::string val = tok.substr(eq + 1);
        if      (key == "eps")        m.eps        = std::stof(val);
        else if (key == "min_pts")    m.min_pts    = std::stoi(val);
        else if (key == "n_clusters") m.n_clusters = std::stoi(val);
        else if (key == "n_noise")    m.n_noise    = std::stoi(val);
        else if (key == "sizes") {
            std::istringstream sv(val);
            std::string num;
            while (std::getline(sv, num, ','))
                if (!num.empty())
                    m.sizes.push_back(std::stoull(num));
        }
    }
    return m;
}

// ─────────────────────────────────────────────────────────────────────────────
// Minimal binary PLY reader (our fixed schema only)
//
// Per-vertex binary layout (little-endian, packed, 19 bytes):
//   float  x      offset  0
//   float  y      offset  4
//   float  z      offset  8
//   int32  label  offset 12  (not used here; ground truth is in the meta)
//   uint8  r,g,b  offset 16  (not used here)
// ─────────────────────────────────────────────────────────────────────────────

static constexpr std::size_t VERTEX_STRIDE = 19; // bytes per vertex

struct PlyCloud {
    PlyMeta            meta;
    std::vector<float> x, y, z;
};

static bool str_starts_with(const std::string &s, const char *prefix) {
    const std::size_t n = std::strlen(prefix);
    return s.size() >= n && s.compare(0, n, prefix) == 0;
}

static PlyCloud load_ply(const fs::path &path) {
    std::ifstream f(path, std::ios::binary);
    if (!f)
        throw std::runtime_error("Cannot open: " + path.string());

    PlyCloud cloud;
    std::string line;
    std::size_t n_verts    = 0;
    bool        meta_found = false;

    // ── ASCII header ─────────────────────────────────────────────────────────
    while (std::getline(f, line)) {
        // Strip trailing \r for cross-platform robustness.
        if (!line.empty() && line.back() == '\r')
            line.pop_back();

        if (str_starts_with(line, "comment vdbscan")) {
            // "comment " is 8 chars; hand the rest to the meta parser.
            cloud.meta = parse_meta(line.substr(8));
            meta_found = true;
        } else if (str_starts_with(line, "element vertex ")) {
            n_verts = std::stoull(line.substr(15));
        } else if (line == "end_header") {
            break;
        }
    }

    if (!meta_found)
        throw std::runtime_error("No 'vdbscan' comment in header: " + path.string());
    if (n_verts == 0)
        throw std::runtime_error("Zero vertices in: " + path.string());

    // ── Binary body ──────────────────────────────────────────────────────────
    std::vector<std::uint8_t> buf(n_verts * VERTEX_STRIDE);
    f.read(reinterpret_cast<char *>(buf.data()),
           static_cast<std::streamsize>(buf.size()));
    if (!f)
        throw std::runtime_error("Truncated binary data in: " + path.string());

    cloud.x.resize(n_verts);
    cloud.y.resize(n_verts);
    cloud.z.resize(n_verts);

    for (std::size_t i = 0; i < n_verts; ++i) {
        const std::uint8_t *p = buf.data() + i * VERTEX_STRIDE;
        std::memcpy(&cloud.x[i], p + 0, 4);
        std::memcpy(&cloud.y[i], p + 4, 4);
        std::memcpy(&cloud.z[i], p + 8, 4);
    }

    return cloud;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Returns per-cluster point counts, sorted ascending (noise label 0 excluded).
static std::vector<std::size_t>
sorted_cluster_sizes(const std::vector<std::size_t> &labels) {
    std::map<std::size_t, std::size_t> counts;
    for (auto l : labels)
        if (l != 0)
            ++counts[l];
    std::vector<std::size_t> sizes;
    sizes.reserve(counts.size());
    for (const auto &kv : counts)
        sizes.push_back(kv.second);
    std::sort(sizes.begin(), sizes.end());
    return sizes;
}

static std::string format_sizes(const std::vector<std::size_t> &v) {
    std::string s;
    for (std::size_t i = 0; i < v.size(); ++i) {
        if (i) s += ',';
        s += std::to_string(v[i]);
    }
    return s;
}

// ─────────────────────────────────────────────────────────────────────────────
// Integration test suite
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("Synthetic PLY files: vdbscan matches sklearn ground truth",
          "[synthetic]") {
    const fs::path dir{SYNTHETIC_DIR};

    if (!fs::is_directory(dir)) {
        FAIL("SYNTHETIC_DIR not found: " << dir.string()
             << "\n  Run 'task gen:synthetic' first.");
    }

    std::vector<fs::path> files;
    for (const auto &entry : fs::directory_iterator(dir))
        if (entry.path().extension() == ".ply")
            files.push_back(entry.path());

    if (files.empty()) {
        FAIL("No .ply files found in " << dir.string()
             << "\n  Run 'task gen:synthetic' first.");
    }

    std::sort(files.begin(), files.end());

    for (const auto &ply_path : files) {
        DYNAMIC_SECTION(ply_path.stem().string()) {
            // ── Load ─────────────────────────────────────────────────────────
            PlyCloud cloud = load_ply(ply_path);
            const PlyMeta &meta = cloud.meta;
            const std::size_t n = cloud.x.size();

            INFO("file        : " << ply_path.string());
            INFO("eps         : " << meta.eps);
            INFO("min_pts     : " << meta.min_pts);
            INFO("total points: " << n);
            INFO("ref clusters: " << meta.n_clusters);
            INFO("ref noise   : " << meta.n_noise);
            INFO("ref sizes   : " << format_sizes(meta.sizes));

            // ── Run vdbscan ──────────────────────────────────────────────────
            PointCloud pc(std::move(cloud.x), std::move(cloud.y), std::move(cloud.z));
            const auto result = dbscan(pc, meta.eps,
                                       static_cast<uint_fast16_t>(meta.min_pts));

            const std::vector<std::size_t> actual_sizes =
                sorted_cluster_sizes(result.labels);

            const std::size_t found_k = actual_sizes.size();
            const std::size_t found_noise =
                std::count(result.labels.begin(), result.labels.end(),
                           std::size_t{0});

            INFO("vdbscan clusters: " << found_k);
            INFO("vdbscan noise   : " << found_noise);
            INFO("actual sizes    : " << format_sizes(actual_sizes));

            // ── 1. Cluster count ─────────────────────────────────────────────
            CHECK(found_k == static_cast<std::size_t>(meta.n_clusters));

            // ── 2. Noise count ───────────────────────────────────────────────
            {
                const std::size_t ref  = static_cast<std::size_t>(meta.n_noise);
                const std::size_t tol  =
                    std::max(SIZE_TOL,
                             static_cast<std::size_t>(ref * NOISE_TOL_FRAC));
                const std::size_t lo   = ref > tol ? ref - tol : 0;
                const std::size_t hi   = ref + tol;
                INFO("noise tolerance: ±" << tol
                     << "  expected range [" << lo << ", " << hi << "]");
                CHECK(found_noise >= lo);
                CHECK(found_noise <= hi);
            }

            // ── 3. Per-cluster sizes ─────────────────────────────────────────
            // Only meaningful when cluster counts agree; otherwise the size
            // vectors have different lengths and the comparison is misleading.
            if (found_k == static_cast<std::size_t>(meta.n_clusters)) {
                bool sizes_ok = true;
                for (std::size_t i = 0; i < meta.sizes.size(); ++i) {
                    const std::size_t ref = meta.sizes[i];
                    const std::size_t got = actual_sizes[i];
                    const std::size_t diff = ref > got ? ref - got : got - ref;
                    if (diff > SIZE_TOL) {
                        sizes_ok = false;
                        INFO("cluster[" << i << "]: ref=" << ref
                             << " got=" << got
                             << " diff=" << diff
                             << " (tol=" << SIZE_TOL << ")");
                    }
                }
                CHECK(sizes_ok);
            }
        }
    }
}
